### ISSUE TITLE
No CC0 license option?

### ISSUE THREAD

**Issue by therahedwig** [pling-us/opendesktop-issues#5]
There's no option to license something cc0, which is a bit strange, because sometimes I just want to share a pattern or something as a resource and want to make clear I don't care what happens with it(partially, because people tend to be afraid to even use CC-By licensed presets and patterns, due to being just about legally savvy enough to know there's such a thing as license-inheritance, but not much else)

Is there a reason this license is missing?

**Comment by star-buck** [comment]
just not added, we can add it this week.
Is that the one you meant? 
https://creativecommons.org/publicdomain/zero/1.0/
CC0 1.0 Universal (Public Domain)

**Comment by rvs75** [comment]
New license CC0 is added.

**Comment by therahedwig** [comment]
Yes, that's right,thank you very much!
